a = input()
b = input()
sum1= int(a) + int(b)
print("Addition :",sum1)
sum2= int(a) - int(b)
print("Subtraction :",sum2)
sum3= int(a) * int(b)
print("Multiplication :",sum3)
sum4= int(a) / int(b)
print("Divition :",sum4)
